name: 'Build AUR Package'
description: 'Test build an Ungoogled Chromium AUR package in Docker container'
branding:
  icon: user-check
  color: purple
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
    default: 'ungoogled-chromium.git'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
