name: build-aur
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          repo-name: ungoogled-chromium.git
